In [ ]:
# Problem 2
# 2.1
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
import math
from sklearn.linear_model import SGDClassifier
import pylab as pl
import random
import pdb
import sklearn as sk

In [ ]:
def getData(name):
    data = pl.loadtxt('/Users/becca/GitHub/6.867/code_hw2/data/' + name)
    # Returns column matrices
    X = data.T[0:2]
    Y = data.T[2:3]
    return X, Y

In [ ]:
pl.loadtxt('/Users/becca/GitHub/6.867/code_hw2/data/'+ 'data1_train.csv')
def data(dataset, category):
    return getData('data'+str(dataset)+'_'+category+'.csv')

In [ ]:
def sigmoid(z):
    """
    Return Sigmoid of z
    Args:
        Z : array or scalar
    """
    return 1.0 / (1.0 + np.exp(-z))

In [87]:
weights[1:weights.shape[0]]

array([[-0.0081015 ],
       [ 3.88997613]])

In [91]:
def log_likelihood(features, target, weights, lamda):
    scores = np.dot(features, weights)
    ll = np.sum( target*scores - np.log(1 + np.exp(scores)) ) + lamda*(sum(np.square(weights[1:weights.shape[0]])))
    return ll

In [167]:
def logistic_regression(features, target, num_steps, learning_rate, lamda, add_intercept = False):
    
    if add_intercept:
        
        intercept = np.ones((features.shape[0], 1))
        features = np.hstack((intercept, features))
        
    weights = np.zeros(features.shape[1])[np.newaxis].T
    target[target == -1] = 0
    
    intvec = []
    wt1vec = []
    wt2vec = []
    
    for step in xrange(num_steps):
        scores = np.dot(features, weights)
        predictions = sigmoid(scores)

        # Update weights with gradient
        output_error_signal = target - predictions
        gradient = np.dot(features.T, output_error_signal) - lamda*np.vstack((0, 2*weights[1:weights.shape[0]]))
        intvec.append(weights[0])
        wt1vec.append(weights[1])
        wt2vec.append(weights[2])
        weights = weights + learning_rate * gradient

        
        # Print log-likelihood every so often
        if step % 30000 == 0:
            print log_likelihood(features, target, weights, lamda)
        
    return weights, intvec, wt1vec, wt2vec

In [161]:
gradient = np.dot(features.T, output_error_signal) - lamda*np.vstack((0, 2*weights[1:weights.shape[0]]))
gradient
weights += learning_rate * gradient
weights

array([[  6.60686953],
       [ -1.35290255],
       [ 20.74781627]])

In [ ]:
X, Y = data(1, 'train')
lamda = 1e3
clfl2 = sk.linear_model.LogisticRegression(penalty = 'l2', tol = 1e-10, C = 1/lamda, 
                                              fit_intercept = True, random_state = 10, 
                                         max_iter = 1000, intercept_scaling = 1e6)
clfl2.fit(X.T, np.ndarray.flatten(Y).T)
np.array([clfl2.intercept_, clfl2.coef_.T])

In [56]:
target = Y.T
target[target == -1] = 0
features = X.T
intercept = np.ones((features.shape[0], 1))
features = np.hstack((intercept, features))
features.shape
weights = np.zeros(features.shape[1])[np.newaxis].T

scores = np.dot(features, weights)
predictions = sigmoid(scores)
output_error_signal = target - predictions

gradient = np.dot(features.T, output_error_signal)
gradient
learning_rate = 1e-2
weights += learning_rate * gradient


In [141]:
lamda = 1e-15
clfl2 = sk.linear_model.LogisticRegression(penalty = 'l2', tol = 1e-10, C = 1/lamda, 
                                              fit_intercept = True, 
                                         max_iter = 100000, intercept_scaling = 1)
clfl2 =  sk.linear_model.LogisticRegression(fit_intercept=True, intercept_scaling = 1, C = 1/lamda)

clfl2 =  sk.linear_model.LogisticRegression(fit_intercept=True, intercept_scaling = 1, C = 1/lamda)

clfl2.fit(X.T, np.ndarray.flatten(Y).T)
np.array([clfl2.intercept_, clfl2.coef_.T])

array([array([ 6.15191348]), array([[ -1.21605761],
       [ 11.73489311]])], dtype=object)

In [ ]:
from __future__ import division
sum(sum(clfl2.predict(X.T) == Y))/Y.shape[1]*100

In [124]:
Y[0:10]

array([[ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
         0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,
         1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,
         0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
         0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
         0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
         1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
         0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
         0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,
         0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
         1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,
         1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.

In [ ]:
pred = sigmoid(np.dot(np.hstack((intercept, X.T )), weights))
pred[pred >.99] = 1
pred[pred < 0.1] = 0
sum(pred == Y.T) # all corr..

In [185]:
lamda = 1
clfl2 =  sk.linear_model.LogisticRegression(fit_intercept=True, intercept_scaling = 1e6, C = 1/lamda)

clfl2.fit(X.T, np.ndarray.flatten(Y).T)
np.array([clfl2.intercept_, clfl2.coef_.T])

array([array([ 1.22219856]), array([[-0.13252873],
       [ 3.03754647]])], dtype=object)

In [201]:
weights

array([[  5.22905043],
       [ -1.06670115],
       [ 10.38177594]])

Using your code to perform gradient descent, train your model parameters(w,w0)using the trainingdata fromdata1train.csvwithλ= 0. What happens to the weight vector as a function of the numberof iteration of gradient descent? What happens whenλ= 1? Explain

In [200]:
weights, intvec, wt1vec, wt2vec  = logistic_regression(X.T, Y.T, 1000000, 1e-4, 1e-15, add_intercept = True)

[-262.44758467]
[-0.7189834]
[-0.40102614]
[-0.2834591]
[-0.22112648]
[-0.18216839]
[-0.15537327]
[-0.13574639]
[-0.12071378]
[-0.10880959]
[-0.09913569]
[-0.09111002]
[-0.0843383]
[-0.07854363]
[-0.07352564]
[-0.06913566]
[-0.06526097]
[-0.06181452]
[-0.05872796]
[-0.05594688]
[-0.05342739]
[-0.05113368]
[-0.04903626]
[-0.04711058]
[-0.04533608]
[-0.04369536]
[-0.04217361]
[-0.04075817]
[-0.0394381]
[-0.03820394]
[-0.03704745]
[-0.03596141]
[-0.03493949]
[-0.03397608]


In [184]:
weightsl1, intvecl1, wt1vecl1, wt2vecl1  = logistic_regression(X.T, Y.T, 1000000, 1e-3, 1, add_intercept = True)

[-156.76234432]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]
[ 2.65335934]


In [209]:
plt.rcParams.update({'font.size': 15})
fig = plt.figure(figsize=(6,5), dpi=300)

iterations = xrange(1000000)
plt.plot(iterations, intvecl1, 'm-', label = 'w0', linewidth = 3)
plt.plot(iterations, wt1vecl1, 'c-', label = 'w1', linewidth = 3)
plt.plot(iterations, wt2vecl1, 'k-', label = 'w2', linewidth = 3)
plt.xlabel('Iterations')
plt.ylabel('Weight Value')
plt.legend(loc='upper right', title = '')
plt.xticks(rotation = 45)

fig.savefig('1.1 lambda = 1 v2.jpg', bbox_inches='tight')

In [208]:
plt.rcParams.update({'font.size': 15})
fig = plt.figure(figsize=(6,5), dpi=300)
iter = xrange(1000000)
plt.plot(iter, intvec, 'm-', label = 'w0', linewidth = 3)
plt.plot(iter, wt1vec, 'c-', label = 'w1', linewidth = 3)
plt.plot(iter, wt2vec, 'k-', label = 'w2', linewidth = 3)
plt.xlabel('Iterations')
plt.ylabel('Weight Value')
plt.legend(loc='upper right', title = '')
plt.xticks(rotation = 45)
fig.savefig('1.1 lambda = 0 v2.jpg', bbox_inches='tight')

In [171]:
intvec

[array([ 0.]),
 array([ 0.001]),
 array([ 0.00418473]),
 array([ 0.00903675]),
 array([ 0.0148951]),
 array([ 0.02133875]),
 array([ 0.02812063]),
 array([ 0.03509264]),
 array([ 0.04216294]),
 array([ 0.04927282]),
 array([ 0.05638385]),
 array([ 0.06347047]),
 array([ 0.07051548]),
 array([ 0.07750732]),
 array([ 0.08443824]),
 array([ 0.09130316]),
 array([ 0.0980989]),
 array([ 0.10482359]),
 array([ 0.11147632]),
 array([ 0.11805689]),
 array([ 0.12456557]),
 array([ 0.13100301]),
 array([ 0.13737011]),
 array([ 0.14366795]),
 array([ 0.14989773]),
 array([ 0.15606075]),
 array([ 0.16215833]),
 array([ 0.16819184]),
 array([ 0.17416267]),
 array([ 0.18007219]),
 array([ 0.18592175]),
 array([ 0.19171271]),
 array([ 0.19744638]),
 array([ 0.20312405]),
 array([ 0.20874698]),
 array([ 0.21431639]),
 array([ 0.21983347]),
 array([ 0.2252994]),
 array([ 0.23071527]),
 array([ 0.2360822]),
 array([ 0.24140123]),
 array([ 0.24667338]),
 array([ 0.25189965]),
 array([ 0.257081]),
 array(